### ISSUE TITLE
`Chisel` Auto Chisel nearby causes Dropoff to not function

### ISSUE THREAD

**Issue by bowers12** [EnigmaticaModpacks/Enigmatica6#4929]
### Modpack Version

1.2.1

### Describe your issue.

Having a `Chisel` Auto Chisel in the range of Dropoff causes the Dropoff button to not function, and throws a error in the console when you attempt to use it. Removing the Autochisel or moving so the Autochisel is out of range of Dropoff returns normal functionality.

[reproduction clip](https://youtu.be/aUjvtrGUN84)

Snipet from my latest log.
```[28May2022 22:55:09.101] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.NullPointerException: null
	at java.util.EnumMap.typeCheck(Unknown Source) ~[?:1.8.0_321]
	at java.util.EnumMap.put(Unknown Source) ~[?:1.8.0_321]
	at java.util.EnumMap.put(Unknown Source) ~[?:1.8.0_321]
	at java.util.Map.computeIfAbsent(Unknown Source) ~[?:1.8.0_321]
	at team.chisel.common.block.TileAutoChisel.getCapability(TileAutoChisel.java:460) ~[chisel:MC1.16.5-2.0.1-alpha.4]
	at net.minecraftforge.common.capabilities.ICapabilityProvider.getCapability(ICapabilityProvider.java:48) ~[forge:?]
	at scp002.quickstack.message.C2SPacketRequestDropoff.lambda$getNearbyInventories$5(C2SPacketRequestDropoff.java:159) ~[dropoff:4.0.1]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_321]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_321]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_321]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:1.8.0_321]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_321]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_321]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_321]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_321]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_321]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_321]
	at scp002.quickstack.message.C2SPacketRequestDropoff.getNearbyInventories(C2SPacketRequestDropoff.java:165) ~[dropoff:4.0.1]
	at scp002.quickstack.message.C2SPacketRequestDropoff.handle(C2SPacketRequestDropoff.java:62) ~[dropoff:4.0.1]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[forge:?]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_321]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[forge:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[forge:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[forge:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86) ~[forge:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:91) ~[forge:?]
	at java.util.Optional.map(Unknown Source) ~[?:1.8.0_321]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:91) ~[forge:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1413) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_321]```

### Crash Report

_No response_

### Latest Log

https://gist.github.com/bowers12/67e6d39c5ae3725a30ee5679ac8867c2

### Have you modified the modpack?

Yes

### User Modifications

Added Autofish, Auto Attack.
Minor changes to client and server configs, most likely unrelated to chisel or dropoff.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by NielsPilgaard** [comment]
Relayed! :)
