### ISSUE TITLE
Cooking for Blockheads: Cooking Table - clicking this block crashes my game 1.50 &1.51 (release) Ticking Entity

### ISSUE THREAD

**Issue by BattleNachos** [EnigmaticaModpacks/Enigmatica6#5185]
### Modpack Version

1.51

### Describe your issue.

Right clicking the Cooking for Blockheads block "Cooking Table" causes the game to crash with a "ticking entity" error.  The error report: 

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 8/27/22 10:25 PM
Description: Ticking entity

java.lang.ArrayIndexOutOfBoundsException: 27
	at net.blay09.mods.cookingforblockheads.api.capability.KitchenItemProvider.getSimulatedUseCount(KitchenItemProvider.java:37) ~[?:9.3.4] {re:classloading}
	at net.blay09.mods.cookingforblockheads.api.capability.DefaultKitchenItemProvider.findSource(DefaultKitchenItemProvider.java:45) ~[?:9.3.4] {re:classloading}
	at net.blay09.mods.cookingforblockheads.registry.CookingRegistry.findAnyItemStack(CookingRegistry.java:225) ~[?:9.3.4] {re:classloading}
	at net.blay09.mods.cookingforblockheads.registry.CookingRegistry.findSourceCandidates(CookingRegistry.java:239) ~[?:9.3.4] {re:classloading}
	at net.blay09.mods.cookingforblockheads.registry.CookingRegistry.getRecipeStatus(CookingRegistry.java:284) ~[?:9.3.4] {re:classloading}
	at net.blay09.mods.cookingforblockheads.container.RecipeBookContainer.findAndSendItemList(RecipeBookContainer.java:221) ~[?:9.3.4] {re:classloading}
	at net.blay09.mods.cookingforblockheads.container.RecipeBookContainer.func_75142_b(RecipeBookContainer.java:153) ~[?:9.3.4] {re:classloading}
	at net.minecraft.entity.player.ServerPlayerEntity.func_70071_h_(ServerPlayerEntity.java:360) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:ServerPlayerEntityMixin,pl:mixin:APP:cant-sleep-clowns-will-eat-me.mixins.json:ServerPlayerEntityMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:612) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architects_palette.mixins.json:ServerWorldMixin,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:ai.nearby_entity_tracking.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.world_ticking.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:world.tick_scheduler.ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld$$Lambda$42681/1029686359.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(MixinWorldRedstone.java:2190) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,pl:mixin:APP:mixins.integrated_proxy.json:MixinWorldRedstone,pl:mixin:APP:lootr.mixins.json:MixinWorld,pl:mixin:APP:observable.common.json:LevelMixin,pl:mixin:APP:roadrunner.mixins.json:ai.nearby_entity_tracking.WorldMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.chunk_random.WorldMixin,pl:mixin:APP:roadrunner.mixins.json:world.block_entity_ticking.collections.WorldMixin,pl:mixin:APP:roadrunner.mixins.json:world.block_entity_ticking.should_tick_cache.WorldMixin,pl:mixin:APP:roadrunner.mixins.json:world.block_entity_ticking.support_cache.WorldMixin,pl:mixin:APP:roadrunner.mixins.json:world.chunk_access.WorldMixin,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:assets/astralsorcery/astralsorcery.mixins.json:MixinWorld,pl:mixin:APP:flywheel.mixins.json:TileWorldHookMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:405) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architects_palette.mixins.json:ServerWorldMixin,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:ai.nearby_entity_tracking.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.world_ticking.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:world.tick_scheduler.ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$41572/1963588077.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.blay09.mods.cookingforblockheads.api.capability.KitchenItemProvider.getSimulatedUseCount(KitchenItemProvider.java:37) ~[?:9.3.4] {re:classloading}
	at net.blay09.mods.cookingforblockheads.api.capability.DefaultKitchenItemProvider.findSource(DefaultKitchenItemProvider.java:45) ~[?:9.3.4] {re:classloading}
	at net.blay09.mods.cookingforblockheads.registry.CookingRegistry.findAnyItemStack(CookingRegistry.java:225) ~[?:9.3.4] {re:classloading}
	at net.blay09.mods.cookingforblockheads.registry.CookingRegistry.findSourceCandidates(CookingRegistry.java:239) ~[?:9.3.4] {re:classloading}
	at net.blay09.mods.cookingforblockheads.registry.CookingRegistry.getRecipeStatus(CookingRegistry.java:284) ~[?:9.3.4] {re:classloading}
	at net.blay09.mods.cookingforblockheads.container.RecipeBookContainer.findAndSendItemList(RecipeBookContainer.java:221) ~[?:9.3.4] {re:classloading}
	at net.blay09.mods.cookingforblockheads.container.RecipeBookContainer.func_75142_b(RecipeBookContainer.java:153) ~[?:9.3.4] {re:classloading}
	at net.minecraft.entity.player.ServerPlayerEntity.func_70071_h_(ServerPlayerEntity.java:360) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:ServerPlayerEntityMixin,pl:mixin:APP:cant-sleep-clowns-will-eat-me.mixins.json:ServerPlayerEntityMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:612) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architects_palette.mixins.json:ServerWorldMixin,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:ai.nearby_entity_tracking.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.world_ticking.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:world.tick_scheduler.ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld$$Lambda$42681/1029686359.accept(Unknown Source) ~[?:?] {}
-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.entity.player.ServerPlayerEntity)
	Entity ID: 26
	Entity Name: PresidentComacho
	Entity's Exact location: -1397.20, 67.00, -217.83
	Entity's Block location: World: (-1398,67,-218), Chunk: (at 10,4,6 in -88,-14; contains blocks -1408,0,-224 to -1393,255,-209), Region: (-3,-1; contains chunks -96,-32 to -65,-1, blocks -1536,0,-512 to -1025,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(MixinWorldRedstone.java:2190) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,pl:mixin:APP:mixins.integrated_proxy.json:MixinWorldRedstone,pl:mixin:APP:lootr.mixins.json:MixinWorld,pl:mixin:APP:observable.common.json:LevelMixin,pl:mixin:APP:roadrunner.mixins.json:ai.nearby_entity_tracking.WorldMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.chunk_random.WorldMixin,pl:mixin:APP:roadrunner.mixins.json:world.block_entity_ticking.collections.WorldMixin,pl:mixin:APP:roadrunner.mixins.json:world.block_entity_ticking.should_tick_cache.WorldMixin,pl:mixin:APP:roadrunner.mixins.json:world.block_entity_ticking.support_cache.WorldMixin,pl:mixin:APP:roadrunner.mixins.json:world.chunk_access.WorldMixin,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:assets/astralsorcery/astralsorcery.mixins.json:MixinWorld,pl:mixin:APP:flywheel.mixins.json:TileWorldHookMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:405) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architects_palette.mixins.json:ServerWorldMixin,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:ai.nearby_entity_tracking.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.world_ticking.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:world.tick_scheduler.ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['PresidentComacho'/26, l='ServerLevel[Iaz]', x=-1397.20, y=67.00, z=-217.83]]
	Chunk stats: ServerChunkCache: 4170
	Level dimension: minecraft:overworld
	Level spawn location: World: (-320,62,-192), Chunk: (at 0,3,0 in -20,-12; contains blocks -320,0,-192 to -305,255,-177), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 13745134 game time, 13189657 day time
	Level name: Iaz
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 10985 (now: false), thunder time: 123427 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$41572/1963588077.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3084654528 bytes (2941 MB) / 6719275008 bytes (6408 MB) up to 7695499264 bytes (7339 MB)
	CPUs: 16
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8256m -Xms256m
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.39.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.39
	FML Language Providers: 
		javafml@36.2
		minecraft@1
		kotlinforforge@1.17.0
	

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Darkere** [comment]
This looks like it is potentially related to the item you are holding while clicking it?

**Comment by BattleNachos** [comment]
I just tested it to be sure.  Same crash with empty hand, and empty offhand.

**Comment by NielsPilgaard** [comment]
Do you have anything that "extends" your inventory, backpacks etc?

**Comment by BattleNachos** [comment]
I'm using Sophisticated Backpacks Gold Backpack with Pickup Upgrade and Advanced Magnet Upgrade.

**Comment by BattleNachos** [comment]
Removing the backpack does not prevent the error.

**Comment by BattleNachos** [comment]
Removing all of my Curios does not prevent the error.

**Comment by Darkere** [comment]
After looking at the code the issue has nothing to do with your player. Appears that it is looking for a connected inventory. Like a fridge or something like that.

**Comment by BattleNachos** [comment]
Destroying the fridge does not prevent the error.  Later I'll play around with destroying various CookingForBlockhead things in my kitchen.

**Comment by BattleNachos** [comment]
FIXED - I did a full rebuild of my kitchen it all works now.  I had a cabinet that somehow had double capacity, I think that was the issue.
