### ISSUE TITLE
Interaction Issue with Rubidium.

### ISSUE THREAD

**Issue by Splutty** [EnigmaticaModpacks/Enigmatica6#5329]
### Modpack Version

E6E 1.6.2

### Describe your issue.

Not really an E6E issue, since I've added Rubidium myself. But there's a weird interaction between buuz's stuff and Rubidium which crashes me on login.

Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?]
	at com.buuz135.industrial.utils.FluidUtils.getFluidColor(FluidUtils.java:41) ~[industrialforegoing:3.2.14.7]
	at com.buuz135.industrial.proxy.client.ClientProxy.lambda$run$10(ClientProxy.java:181) ~[industrialforegoing:3.2.14.7]
	at me.jellysquid.mods.sodium.client.model.quad.blender.FlatBiomeColorBlender.getColors(FlatBiomeColorBlender.java:21) ~[rubidium:?]
	at me.jellysquid.mods.sodium.client.model.quad.blender.ConfigurableColorBlender.getColors(ConfigurableColorBlender.java:34) ~[rubidium:?]

Not sure if buuz can have a look? Or someone can forward this? Obviously not something that needs fixing in E6E, but also not something I can really post on the IF github either.

### Have you modified the modpack?

Yes

### User Modifications

Rubidium, BorderlessWindow

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
I recommend that you report this to IF and Rubidium :)
